<?php
/**
 * Copyright © 2021 Roma Technology Limited. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<section class="zohoformwidget">
  <div id="zohoform">
  </div>
  <script type="text/javascript">(function() {
    try{
      var f = document.createElement("iframe");   
      f.src = '<?= $block->getFormUrl(); ?>';
      f.style.border="none";                                           
      f.style.height="1322px";
      f.style.width="90%";
      f.style.transition="all 0.5s ease";// No I18N
      var d = document.getElementById("zohoform");
      d.appendChild(f);
      window.addEventListener('message', function () {
        var zf_ifrm_data = event.data.split("|");
        var zf_perma = zf_ifrm_data[0];
        var zf_ifrm_ht_nw = ( parseInt(zf_ifrm_data[1], 10) + 15 ) + "px";
        var iframe = document.getElementById("zohoform").getElementsByTagName("iframe")[0];
        if ( (iframe.src).indexOf('formperma') > 0 && (iframe.src).indexOf(zf_perma) > 0 ) {
          var prevIframeHeight = iframe.style.height;
          if ( prevIframeHeight != zf_ifrm_ht_nw ) {
            iframe.style.height = zf_ifrm_ht_nw;
          }   
        }
      }, false);
    } catch(e){}
  })();
  </script>
</section>